version: 0.2

phases:
  pre_build:
    commands:
      - echo "entered the pre-build phase, building zip file"
      - chmod +x scripts/dist.sh && scripts/dist.sh
      - ls .
      - ls dist
      - echo "fin commands"
  build:
    commands:
      - echo "Entered the build phase, installing dependencies"
      - npm install
  post_build:
    commands:
      - echo "Entered the post-build phase, proceeding to deploy the artifact"
artifacts:
  files: "**/*"
  base_directory: "."
deploy:
  artifacts: dist/aws-eb-typescript-app.zip
