version: 0.2

phases:
  pre_build:
    commands:
      - echo "entered the pre-build phase, building zip file"
      - npm install
      - npm run build
      - chmod +x scripts/dist.sh && scripts/dist.sh
      - stat dist || mkdir dist
      - zip $npm_package_name.zip -r dist package.json package-lock.json
      - ls .
      - ls dist
      - ls scripts
      - echo "fin commands"
  build:
    commands:
      - echo "Entered the build phase, installing dependencies"
  post_build:
    commands:
      - echo "Entered the post-build phase, proceeding to deploy the artifact"
artifacts:
  files: "**/*"
  base-directory: ""
deploy:
  artifacts: dist/aws-eb-typescript-app.zip
