version: 0.2
phases:
  pre_build:
    commands:
      - echo "entered the pre-build phase, building zip file"
      - sudo chmod +x scripts/dist.sh && sudo scripts/dist.sh
      - echo "fin commands"
  build:
    commands:
      - echo "Entered the build phase, installing dependencies"
      - npm install
  post_build:
    commands:
      - echo "Entered the post-build phase, proceeding to deploy the artifact"
deploy:
  artifacts: dist/aws-eb-typescript-app.zip
